Repository ArtemLyah/cloneoverflow, pull requests merged in 2024-03, with the labels that each got.

#13 endpoint #4 Create an endpoint for updating user profile
  backend/src/controllers/user.controller.ts
  backend/src/dtos/user.update.dto.ts
  backend/src/index.ts
  backend/src/mappers/user.mapper.ts
  backend/src/repositories/answer.repository.ts
  backend/src/responses/userUpdate.response.ts
  backend/src/routers/user.ts
  backend/src/services/user.service.ts
  backend/src/types/database/DbAnswer.ts
  backend/src/utils/exceptions/NoEntityWithIdException.ts
Labels: endpoint

#17 repository #1: Create a repository for questions
  backend/src/repositories/question.repository.ts
  backend/src/types/database/DbQuestion.ts
Labels: repository

#18 endpoint #7: created endpoint to get user answers
  .gitignore
  backend/prisma/schema.prisma
  backend/src/controllers/auth.controller.ts
  backend/src/controllers/user.controller.ts
  backend/src/dtos/pagination.dto.ts
  backend/src/dtos/user.getAnswers.dto.ts
  backend/src/index.ts
  backend/src/mappers/auth.mapper.ts
  backend/src/mappers/user.mapper.ts
  backend/src/middlewares/authAccess.ts
  backend/src/middlewares/errorHandler.ts
  backend/src/middlewares/prismaErrorHandler.ts
  backend/src/middlewares/validation.ts
  backend/src/repositories/answer.repository.ts
  backend/src/responses/auth.getMe.response.ts
  backend/src/responses/pagination.response.ts
  backend/src/responses/user.getAnswers.response.ts
  backend/src/responses/user.update.response.ts
  backend/src/routers/auth.ts
  backend/src/routers/user.ts
  backend/src/services/answer.service.ts
  backend/src/services/auth.service.ts
  backend/src/services/user.service.ts
  backend/src/types/OrderBy.ts
  backend/src/types/PaginatedData.ts
  backend/src/types/Requests.ts
  backend/src/types/TokenPayload.ts
  backend/src/types/database/DbAnswer.ts
  backend/src/utils/DatabaseUtils.ts
  backend/src/utils/exceptions/ValidationException.ts
  backend/src/utils/functionUtils.ts
Labels: endpoint

#19 endpoint #14: created an endpoint to create question
  backend/src/controllers/question.controller.ts
  backend/src/dtos/question.create.dto.ts
  backend/src/index.ts
  backend/src/mappers/question.mapper.ts
  backend/src/repositories/question.repository.ts
  backend/src/responses/question.create.response.ts
  backend/src/routers/question.ts
  backend/src/services/question.service.ts
  backend/src/types/database/DbQuestion.ts
Labels: endpoint

#26 endpoint #16 #21: Created endpoint for creating answer and getting list of questions
  backend/src/controllers/answer.controller.ts
  backend/src/controllers/auth.controller.ts
  backend/src/controllers/question.controller.ts
  backend/src/controllers/user.controller.ts
  backend/src/dtos/answer.create.dto.ts
  backend/src/dtos/user.getQuestions.dto.ts
  backend/src/index.ts
  backend/src/mappers/answer.mapper.ts
  backend/src/mappers/user.mapper.ts
  backend/src/middlewares/authAccess.ts
  backend/src/repositories/answer.repository.ts
  backend/src/repositories/question.repository.ts
  backend/src/responses/answer.create.response.ts
  backend/src/responses/user.getQuestion.response.ts
  backend/src/routers/answer.ts
  backend/src/routers/user.ts
  backend/src/services/answer.service.ts
  backend/src/services/auth.service.ts
  backend/src/services/question.service.ts
  backend/src/services/user.service.ts
  backend/src/types/database/DbAnswer.ts
  backend/src/utils/DatabaseUtils.ts
Labels: endpoint, answer, user

#20 endpoint #15: Created an endpoint for updating question
  backend/src/controllers/question.controller.ts
  backend/src/dtos/question.create.dto.ts
  backend/src/dtos/question.update.dto.ts
  backend/src/mappers/question.mapper.ts
  backend/src/responses/question.update.response.ts
  backend/src/routers/question.ts
  backend/src/services/question.service.ts
Labels: endpoint

#27 endpoint #3: Created endpoint to get user profile info
  backend/src/config/index.ts
  backend/src/controllers/auth.controller.ts
  backend/src/controllers/user.controller.ts
  backend/src/mappers/user.mapper.ts
  backend/src/responses/ok.response.ts
  backend/src/responses/user.getProfile.response.ts
  backend/src/routers/user.ts
  backend/src/services/user.service.ts
  backend/src/types/database/DbUser.ts
Labels: endpoint, user

#29 frontend: created user profile page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/dtos/auth.changePassword.dto.ts
  frontend/src/api/dtos/auth.signup.dto.ts
  frontend/src/api/dtos/pagination.dto.ts
  frontend/src/api/dtos/user.getAnswer.dto.ts
  frontend/src/api/dtos/user.getQuestion.dto.ts
  frontend/src/api/dtos/user.update.dto.ts
  frontend/src/api/index.ts
  frontend/src/api/response/ok.message.ts
  frontend/src/api/response/user.get.response.ts
  frontend/src/api/response/user.getAnswers.response.ts
  frontend/src/api/response/user.getProfile.response.ts
  frontend/src/api/response/user.getQuestion.response.ts
  frontend/src/api/services/auth.service.ts
  frontend/src/api/services/user.service.ts
  frontend/src/api/types/AuthTokens.ts
  frontend/src/api/types/Pagination.ts
  frontend/src/api/types/QuestionStatus.ts
  frontend/src/api/types/ServerException.ts
  frontend/src/api/types/UserStatus.ts
  frontend/src/app.css
  frontend/src/components/menu/index.tsx
  frontend/src/components/menu/menu.css
  frontend/src/components/taglist/taglist.css
  frontend/src/components/taglist/taglist.tsx
  frontend/src/components/username/username.css
  frontend/src/components/username/username.tsx
  frontend/src/contexts/authContext.tsx
  frontend/src/hooks/useAuth.ts
  frontend/src/pages/auth/SignupData.ts
  frontend/src/pages/auth/auth.css
  frontend/src/pages/auth/login.tsx
  frontend/src/pages/auth/signup.tsx
  frontend/src/pages/user/index.tsx
  frontend/src/pages/user/profile.css
  frontend/src/pages/user/tabs/user-about-tab/index.tsx
  frontend/src/pages/user/tabs/user-about-tab/user-about-tab.css
  frontend/src/pages/user/tabs/user-answers-tab/index.tsx
  frontend/src/pages/user/tabs/user-answers-tab/user-answers-tab.css
  frontend/src/pages/user/tabs/user-questions-tab/index.tsx
  frontend/src/pages/user/tabs/user-questions-tab/user-questions-tab.css
  frontend/src/pages/user/tabs/user-settings-tab/index.tsx
  frontend/src/pages/user/tabs/user-settings-tab/user-settings-tab.css
  frontend/src/routers/PrivateRoute.tsx
  frontend/src/routers/routes.tsx
  frontend/src/utils/stringUtils.ts
  frontend/src/utils/urls.ts
  frontend/src/utils/withAuthorisation.ts
Labels: flow

#28 endpoint #22: Created an endpoint for updating answer
  backend/src/controllers/answer.controller.ts
  backend/src/dtos/answer.update.dto.ts
  backend/src/mappers/answer.mapper.ts
  backend/src/responses/answer.update.response.ts
  backend/src/routers/answer.ts
  backend/src/services/answer.service.ts
Labels: endpoint, answer
